### ISSUE TITLE
"Shared libraries" error (on musl?)

### ISSUE THREAD

**Issue by emacsomancer** [shuichiro-makigaki/docker-texlive-2016#2]
When I try to run `xelatex` I'm getting a "shared libraries" error:
     
     docker run --rm --volume /home/emacsomancer/.fonts:/usr/share/fonts/external/ --volume $PWD:/workdir --workdir /workdir --user 1001:1001 makisyu/texlive-2016 xelatex mytexdoc.tex

     xelatex: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

Does this build assume a glibc base for the host? (I don't know enough about the internals of Dockerfiles)  I'm running on Void linux using musl libc. 

Or is this error from some other issue?

(This other Docker Texlive: https://github.com/thomasWeise/docker-texlive seems to work for me, but it seems to have a rather old version of Texlive.)

**Comment by shuichiro-makigaki** [comment]
Could you try docker-texlive-2018 or 2019?
